In [12]:
import pandas as pd
import seaborn as sns
from pathlib import Path

In [13]:
ROOT_DIR = Path().resolve(strict=True).parent
DATA_DIR = f"{ROOT_DIR}/data/"

pd.options.mode.chained_assignment = None

columns_to_skip = [
        "Name",
        "Stock Price"
    ]
df = pd.read_csv(f"{DATA_DIR}/interim/null_filled.csv", index_col=0, usecols=lambda x: x not in columns_to_skip)

In [14]:
s = list(df.columns)
s.sort()
s

['Abnormal Gains (Losses)',
 'Accounts & Notes Receivable',
 'Cash from (Repayment of) Debt',
 'Cash from (Repurchase of) Equity',
 'Cash, Cash Equivalents & Short Term Investments',
 'Change in Accounts Payable',
 'Change in Accounts Receivable',
 'Change in Fixed Assets & Intangibles',
 'Change in Inventories',
 'Change in Other',
 'Change in Working Capital',
 'Cost of Revenue',
 'Depreciation & Amortization',
 'Depreciation & Amortization.1',
 'Dividends Paid',
 'Fiscal Year',
 'Gross Profit',
 'Income (Loss) from Continuing Operations',
 'Income Tax (Expense) Benefit, Net',
 'Interest Expense, Net',
 'Inventories',
 'Long Term Debt',
 'Long Term Investments & Receivables',
 'Net Cash from Acquisitions & Divestitures',
 'Net Cash from Financing Activities',
 'Net Cash from Investing Activities',
 'Net Cash from Operating Activities',
 'Net Change in Cash',
 'Net Change in Long Term Investment',
 'Net Extraordinary Gains (Losses)',
 'Net Income',
 'Net Income (Common)',
 'Net Income/Starting Line',
 'Non-Cash Items',
 'Non-Operating Income (Loss)',
 'Operating Expenses',
 'Operating Income (Loss)',
 'Other Long Term Assets',
 'Payables & Accruals',
 'Pretax Income (Loss)',
 'Pretax Income (Loss), Adj.',
 'Property, Plant & Equipment, Net',
 'Research & Development',
 'Retained Earnings',
 'Revenue',
 'Sector',
 'Selling, General & Administrative',
 'Share Capital & Additional Paid-In Capital',
 'Shares (Basic)',
 'Shares (Diluted)',
 'Short Term Debt',
 'Ticker',
 'Total Assets',
 'Total Current Assets',
 'Total Current Liabilities',
 'Total Equity',
 'Total Liabilities',
 'Total Liabilities & Equity',
 'Total Noncurrent Assets',
 'Total Noncurrent Liabilities',
 'Treasury Stock']

In [15]:
df = df.sort_values(by=['Ticker','Fiscal Year'], ascending=True)
df.head(12)

,Ticker,Fiscal Year,Shares (Basic),Sector,Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",...,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash
0,A,2008,363000000.0,Healthcare,371000000.0,5.774000e+09,-2.578000e+09,3.196000e+09,-2.401000e+09,-1.697000e+09,...,756000000,-140000000.0,150000000.0,-1.720000e+08,-3.850000e+08,0.0,1.600000e+07,-790000000.0,-7.880000e+08,-421000000
1,A,2009,346000000.0,Healthcare,346000000.0,4.481000e+09,-2.189000e+09,2.292000e+09,-2.245000e+09,-1.603000e+09,...,408000000,-127000000.0,94000000.0,4.300000e+07,-4.000000e+06,0.0,7.480000e+08,-86000000.0,6.470000e+08,1074000000
2,A,2010,347000000.0,Healthcare,353000000.0,5.444000e+09,-2.514000e+09,2.930000e+09,-2.364000e+09,-1.752000e+09,...,718000000,-114000000.0,38000000.0,-1.108000e+09,-1.174000e+09,0.0,7.180000e+08,-112000000.0,6.010000e+08,170000000
3,A,2011,347000000.0,Healthcare,355000000.0,6.615000e+09,-3.086000e+09,3.529000e+09,-2.458000e+09,-1.809000e+09,...,1260000000,-170000000.0,16000000.0,-9.700000e+07,1.294000e+09,0.0,-1.500000e+09,-193000000.0,-1.693000e+09,878000000
4,A,2012,348000000.0,Healthcare,353000000.0,6.858000e+09,-3.254000e+09,3.604000e+09,-2.485000e+09,-1.817000e+09,...,1228000000,-194000000.0,5000000.0,-2.257000e+09,-2.366000e+09,-104000000.0,1.500000e+08,-72000000.0,-3.500000e+07,-1174000000
5,A,2013,341000000.0,Healthcare,345000000.0,3.894000e+09,-1.987000e+09,1.907000e+09,-1.521000e+09,-1.184000e+09,...,1152000000,-193000000.0,12000000.0,-4.200000e+07,-2.480000e+08,-156000000.0,3.470000e+08,-739000000.0,-5.540000e+08,324000000
6,A,2014,333000000.0,Healthcare,338000000.0,4.048000e+09,-2.072000e+09,1.976000e+09,-1.557000e+09,-1.199000e+09,...,731000000,-191000000.0,1000000.0,-3.600000e+07,-2.300000e+08,-176000000.0,9.900000e+07,-12000000.0,-1.170000e+08,353000000
7,A,2015,333000000.0,Healthcare,335000000.0,4.038000e+09,-1.997000e+09,2.041000e+09,-1.519000e+09,-1.189000e+09,...,512000000,-86000000.0,0.0,-7.200000e+07,-4.000000e+08,-133000000.0,0.000000e+00,-209000000.0,-1.089000e+09,-1025000000
8,A,2016,326000000.0,Healthcare,329000000.0,4.202000e+09,-2.005000e+09,2.197000e+09,-1.582000e+09,-1.253000e+09,...,793000000,-139000000.0,1000000.0,-2.610000e+08,-2.380000e+08,-150000000.0,2.620000e+08,-372000000.0,-2.680000e+08,286000000
9,A,2017,322000000.0,Healthcare,326000000.0,4.472000e+09,-2.063000e+09,2.409000e+09,-1.568000e+09,-1.229000e+09,...,889000000,-176000000.0,0.0,-1.260000e+08,-3.050000e+08,-170000000.0,1.100000e+08,-128000000.0,-2.020000e+08,389000000
10,A,2018,321000000.0,Healthcare,325000000.0,4.914000e+09,-2.234000e+09,2.680000e+09,-1.776000e+09,-1.389000e+09,...,1087000000,-176000000.0,0.0,-5.160000e+08,-7.050000e+08,-191000000.0,-2.100000e+08,-366000000.0,-7.970000e+08,-432000000
11,A,2019,314000000.0,Healthcare,318000000.0,5.163000e+09,-2.358000e+09,2.805000e+09,-1.864000e+09,-1.460000e+09,...,1021000000,-155000000.0,0.0,-1.408000e+09,-1.590000e+09,-206000000.0,6.000000e+08,-669000000.0,-2.990000e+08,-866000000

In [16]:
df.loc[df['Ticker'] == df['Ticker'].shift(periods=1), 'capex'] = (
    df['Property, Plant & Equipment, Net'].shift(periods=1)
    - df['Property, Plant & Equipment, Net']
    + df['Depreciation & Amortization']
)

In [17]:
df.head()

,Ticker,Fiscal Year,Shares (Basic),Sector,Shares (Diluted),Revenue,Cost of Revenue,Gross Profit,Operating Expenses,"Selling, General & Administrative",...,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,capex
0,A,2008,363000000.0,Healthcare,371000000.0,5.774000e+09,-2.578000e+09,3.196000e+09,-2.401000e+09,-1.697000e+09,...,-140000000.0,150000000.0,-1.720000e+08,-3.850000e+08,0.0,1.600000e+07,-790000000.0,-7.880000e+08,-421000000,NaN
1,A,2009,346000000.0,Healthcare,346000000.0,4.481000e+09,-2.189000e+09,2.292000e+09,-2.245000e+09,-1.603000e+09,...,-127000000.0,94000000.0,4.300000e+07,-4.000000e+06,0.0,7.480000e+08,-86000000.0,6.470000e+08,1074000000,-21000000.0
2,A,2010,347000000.0,Healthcare,353000000.0,5.444000e+09,-2.514000e+09,2.930000e+09,-2.364000e+09,-1.752000e+09,...,-114000000.0,38000000.0,-1.108000e+09,-1.174000e+09,0.0,7.180000e+08,-112000000.0,6.010000e+08,170000000,-135000000.0
3,A,2011,347000000.0,Healthcare,355000000.0,6.615000e+09,-3.086000e+09,3.529000e+09,-2.458000e+09,-1.809000e+09,...,-170000000.0,16000000.0,-9.700000e+07,1.294000e+09,0.0,-1.500000e+09,-193000000.0,-1.693000e+09,878000000,-26000000.0
4,A,2012,348000000.0,Healthcare,353000000.0,6.858000e+09,-3.254000e+09,3.604000e+09,-2.485000e+09,-1.817000e+09,...,-194000000.0,5000000.0,-2.257000e+09,-2.366000e+09,-104000000.0,1.500000e+08,-72000000.0,-3.500000e+07,-1174000000,-158000000.0

In [18]:
# df = df.groupby(["Ticker", "Fiscal Year"]).mean()

In [19]:
fcf = df['Net Cash from Operating Activities'] - df['Net Cash from Financing Activities']
df['fcf'] = fcf
owners_earnings = df['Net Income'] + df['Depreciation & Amortization'] + df['Change in Working Capital'] + df['Net Cash from Financing Activities']
df['owners_earnings'] = owners_earnings

df['roa'] = (df['Net Income'] /  df['Total Assets'] )
df['roe'] = (df['Net Income'] /  df['Total Equity']) 
df['roc'] = (df['Operating Income (Loss)'] /  df['Total Assets'])

df['current_ratio'] = df['Total Current Assets'] / df['Total Current Liabilities']
df['quick_ratio'] = (df['Accounts & Notes Receivable'] + df['Cash, Cash Equivalents & Short Term Investments']) / df['Total Current Liabilities'] 

df['gross_margin'] = df['Gross Profit'] / df['Revenue']
df['net_income_margin'] = df['Net Income'] / df['Revenue']
df['owners_earnings_to_net_income'] = owners_earnings / df['Net Income']
df['rd_to_net_income'] = df['Research & Development'] / df['Net Income']
df['capex_to_net_income'] = df['capex'] / df['Net Income']
df['fcf_margin'] = fcf / df['Revenue']

df['net_income_growth_rate'] = df["Net Income"].pct_change()
df['revenue_growth_rate'] = df["Net Income"].pct_change()
df['capex_growth_rate'] = df["Net Income"].pct_change()

In [20]:
resumed_df = df[
    [
        "Ticker",
        "Fiscal Year",
        "Revenue",
        "Cost of Revenue",
        "Net Income",

        "fcf",
        "owners_earnings",

        "roa",
        "roe",
        "roc",

        "current_ratio",
        "quick_ratio",

        "gross_margin",
        "net_income_margin",
        "fcf_margin",

        "owners_earnings_to_net_income",
        "rd_to_net_income",
        "capex_to_net_income",

        "net_income_growth_rate", 
    ]
]

In [21]:
RESCALE_VALUE = 100000000

resumed_df['Revenue'] = resumed_df['Revenue'] / RESCALE_VALUE
resumed_df['Cost of Revenue'] = resumed_df['Cost of Revenue'] / RESCALE_VALUE
resumed_df['Net Income'] = resumed_df['Net Income'] / RESCALE_VALUE
resumed_df['fcf'] = resumed_df['fcf'] / RESCALE_VALUE
resumed_df['owners_earnings'] = resumed_df['owners_earnings'] / RESCALE_VALUE

resumed_df = resumed_df.round(2)
resumed_df = resumed_df.fillna(0)

In [22]:
resumed_df.describe()

,Fiscal Year,Revenue,Cost of Revenue,Net Income,fcf,owners_earnings,roa,roe,roc,current_ratio,quick_ratio,gross_margin,net_income_margin,fcf_margin,owners_earnings_to_net_income,rd_to_net_income,capex_to_net_income,net_income_growth_rate
count,20273.000000,20273.000000,20273.000000,20273.000000,20273.000000,20273.000000,20273.00,20273.00,20273.00,20273.00,20273.00,20273.00,20273.00,20273.00,20273.00,20273.000000,20273.000000,20273.00
mean,2014.353426,65.828129,-42.405756,4.744747,11.889434,-0.347633,NaN,NaN,NaN,inf,inf,NaN,NaN,NaN,NaN,-0.156886,0.797179,NaN
std,3.283701,227.722157,166.893362,22.628964,52.012642,27.311165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.274751,351.061244,NaN
min,1998.000000,-0.070000,-3946.050000,-223.540000,-386.260000,-816.210000,-inf,-inf,-inf,0.00,0.00,-inf,-inf,-inf,-inf,-2793.850000,-20144.000000,-inf
25%,2012.000000,2.470000,-23.840000,-0.030000,0.000000,-0.880000,-0.01,-0.02,0.02,1.17,0.61,0.26,-0.02,-0.01,-0.59,0.000000,-0.550000,-0.70
50%,2015.000000,12.490000,-5.490000,0.510000,1.310000,-0.010000,0.04,0.09,0.07,1.81,1.11,0.42,0.05,0.12,0.28,0.000000,-0.060000,-0.02
75%,2017.000000,44.420000,-0.660000,2.930000,7.260000,0.930000,0.08,0.19,0.12,2.96,2.01,0.65,0.11,0.25,1.12,0.000000,0.010000,0.36
max,2020.000000,5239.640000,0.310000,814.170000,1653.100000,932.040000,inf,inf,inf,inf,inf,inf,inf,inf,inf,3246.000000,39076.420000,inf

In [23]:
resumed_df

,Ticker,Fiscal Year,Revenue,Cost of Revenue,Net Income,fcf,owners_earnings,roa,roe,roc,current_ratio,quick_ratio,gross_margin,net_income_margin,fcf_margin,owners_earnings_to_net_income,rd_to_net_income,capex_to_net_income,net_income_growth_rate
0,A,2008,57.74,-25.78,6.93,15.44,-2.74,0.10,0.27,0.11,2.39,1.65,0.55,0.12,0.27,-0.40,-1.02,0.00,0.00
1,A,2009,44.81,-21.89,-0.31,-2.39,6.78,-0.00,-0.01,0.01,3.53,2.75,0.51,-0.01,-0.05,-21.87,20.71,0.68,-1.04
2,A,2010,54.44,-25.14,6.84,1.17,12.33,0.07,0.21,0.06,2.00,1.14,0.54,0.13,0.02,1.80,-0.89,-0.20,-23.06
3,A,2011,66.15,-30.86,10.12,29.53,-9.05,0.11,0.23,0.12,3.03,2.39,0.53,0.15,0.45,-0.89,-0.64,-0.03,0.48
4,A,2012,68.58,-32.54,11.53,12.63,9.42,0.11,0.22,0.11,2.45,1.73,0.53,0.17,0.18,0.82,-0.58,-0.14,0.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20268,ZYXI,2015,0.12,-0.05,-0.03,0.01,-0.02,-0.79,0.72,-0.67,0.37,0.32,0.58,-0.25,0.07,0.61,-0.00,-0.16,-0.53
20269,ZYXI,2016,0.13,-0.04,0.00,0.03,-0.00,0.02,-0.02,0.16,0.44,0.42,0.74,0.01,0.23,-2.35,0.00,3.20,-1.02
20270,ZYXI,2017,0.23,-0.05,0.07,0.11,0.03,0.82,1.50,1.00,2.08,1.93,0.79,0.31,0.47,0.45,0.00,0.05,105.74
20271,ZYXI,2018,0.32,-0.06,0.10,0.13,0.05,0.50,1.03,0.54,2.05,1.85,0.81,0.30,0.41,0.54,0.00,-0.07,0.30
20272,ZYXI,2019,0.45,-0.09,0.09,0.09,0.02,0.34,0.48,0.39,4.34,3.82,0.81,0.21,0.19,0.22,0.00,-0.00,-0.01